server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  profiles:
    active: local

  session:
    store-type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: false
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jinddung2.givemeticon.domain.*
  configuration:
    map-underscore-to-camel-case: true

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
#      show-details: always
      show-components: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#        include: health, info, metrics, prometheus
