server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    include: secret

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jinddung2.givemeticon.*.domain
  configuration:
    map-underscore-to-camel-case: true
