server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    include: secret, oauth, openapi

  session:
    store-type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jinddung2.givemeticon.*.domain
  configuration:
    map-underscore-to-camel-case: true

mail:
  title:
    certification: givemeticon 인증번호 안내
  domain:
    name: http://localhost:8080